fix(dgw): self-signed TLS certificate generation of the Docker image build (#1650)
Fixes this error:
```
Get-Content: Cannot find path '/tmp/gateway-{hostname}.pem' because it does not exist.
Exception: Empty certificate chain!
```
Hit when generating the self-signed TLS certificate generation in the Docker entrypoint.

Co-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>
Co-authored-by: Dahllias <96178300+Dahllias@users.noreply.github.com>